### ISSUE TITLE
[Regression] Auto-complete fails for zshmarks

### ISSUE THREAD

**Issue by protist** [zimfw/zimfw#231]
In a terminal, run `zmanage info` and paste the output below:

```
zsh: command not found: zmanage
```

- `~/.zimrc`: `zmodules=(zshmarks completion)`
- `~/.zshrc`: none
- `~/.bookmarks`: `/tmp|foo`

Description
-----------
From commit 55df5a4, autocompletion fails for [zshmarks](https://github.com/jocelynmallon/zshmarks).
```
$ jump f<tab>
(eval):1: _jump_showmarks_deletemarks: function definition file not found
(eval):1: _jump_showmarks_deletemarks: function definition file not found
(eval):1: _jump_showmarks_deletemarks: function definition file not found
```
Completion works well in the previous commit. I suspect it's something to do with paths being changed?

Steps to reproduce
------------------
* Install zshmarks (e.g. in Arch Linux from the AUR [package](https://aur.archlinux.org/packages/zshmarks-git/). This also installs the module at `/usr/lib/zim/modules/zshmarks`)
* Set up a dummy `~/.bookmarks` file as above
* Install zim 55df5a4
* Autocomplete fails
* Install the previous commit, then run `rm ~/.zcompdump*; compinit`
* Autocomplete works

**Comment by ericbn** [comment]
@protist, does your `.zlogin` file matches the [latest zlogin template](https://github.com/Eriner/zim/blob/a8244a555a62f04f77c4056672c91df15103597b/templates/zlogin)?

We've updated the templates recently.

**Comment by protist** [comment]
I essentially follow the defaults of the [AUR package](https://aur.archlinux.org/packages/zsh-zim-git/) install. The only modification that I've made is to change `/etc/zsh/zimrc`, removing
```
source /usr/lib/zim/templates/zimrc
```
replacing it with my customised zim modules, with
```
source ~/.zimrc
```

I've double checked the other installed files on my system. These are identical to the packaged version.
* `/etc/zsh/zlogin`
* `/etc/zsh/zshrc`
* `/usr/lib/zim/templates/zimrc`
* `/usr/lib/zim/templates/zlogin`
* `/usr/lib/zim/templates/zshrc`

I've also specifically checked the contents of the zlogin files, just in case the packaging was broken somehow.
`/etc/zsh/zlogin` contains
```
source /usr/lib/zim/templates/zlogin
```
`/usr/lib/zim/templates/zlogin` contains the file you linked.

**Comment by ericbn** [comment]
@protist, what about updating zim to `e4e0c55` or a newer commit?

**Comment by protist** [comment]
@ericbn Ah yes, sorry, I initially noticed this regression in the current 5387adb. I was previously using 8aa086c (which was the last working version), and I bisected back to the first failing commit, which was 55df5a4.

**Comment by MeisterP** [comment]
I've stumbled over this problem as well.
I did add zshmarks as a new module a while ago and had to change init.zsh to workaround the issue.
(see https://github.com/MeisterP/zim/commit/73914c93ce9ec0e85a1fab395c67cd8759dcc7f2)

**Comment by ericbn** [comment]
Pushed a new commit that should fix this. Functions starting with `_` where not being zcompiled, and looks like that was the root cause if this issue.

**Comment by protist** [comment]
Thanks @ericbn. Unfortunately the issue is still present as described, after upgrading to 07d32ca, and also after running `rm ~/.zcompdump*; compinit`.

**Comment by ericbn** [comment]
@protist, I don't have Arch Linux, so cannot test with the AUR package. (I'm on Mac OS and looks like there is no brew package for this.)

I cloned the repo directly into the zim modules subdirectory. What I did was:
```
$ gfc git@github.com:jocelynmallon/zshmarks.git ~/.zim/modules/zshmarks
Cloning into '~/.zim/modules/zshmarks'...
remote: Counting objects: 153, done.
remote: Total 153 (delta 0), reused 0 (delta 0), pack-reused 153
Receiving objects: 100% (153/153), 27.84 KiB | 0 bytes/s, done.
Resolving deltas: 100% (61/61), done.
$ tree ~/.zim/modules/zshmarks
~/.zim/modules/zshmarks
├── README.md
├── _jump_showmarks_deletemark
├── functions
│   └── _jump_showmarks_deletemarks -> ../_jump_showmarks_deletemark
├── init.zsh -> zshmarks.plugin.zsh
└── zshmarks.plugin.zsh

1 directory, 5 files
$ echo ${+functions[_jump_showmarks_deletemarks]}
0
```

Then I added `zshmarks` to the `zmodules` array in my `~/.zimrc` file. Then started a new shell:

```
$ echo ${+functions[_jump_showmarks_deletemarks]}
1
```

This process didn't get the auto-completion working, so I could not test the specific scenario where you do:

```
$ jump f<tab>
```

But I was able to confirm that the `_jump_showmarks_deletemarks` function was loaded.

**Comment by protist** [comment]
> But I was able to confirm that the `_jump_showmarks_deletemarks` function was loaded.

Do you say this because of the output of `echo ${+functions[_jump_showmarks_deletemarks]}`? I don't understand what this command does, but if I run this on my system with the current HEAD (07d32ca) installed, I also get `1`. However, I also get `1` after installing the working 8aa086c, or the first broken 55df5a4 (after running `rm ~/.zcompdump*; compinit` in both cases).

> This process didn't get the auto-completion working

This might be because you don't have the `~/.bookmarks` file? You can just create a file here with the contents:
```
/tmp|foo
```

Then, `jump f<tab>` should work.

**Comment by ericbn** [comment]
@protist, can you please test if the changes I'm proposing at #239 do fix this issue for you?

**Comment by protist** [comment]
@ericbn I tried applying the patch to the HEAD (3c96d0b) and installing, and it fixes this issue! Thank you for the fix. Feel free to close this issue when appropriate.

**Comment by ericbn** [comment]
Thanks for reporting and patiently retesting this issue, @protist!

Good to know #239 will fix this! Let's leave this issue open until the fix gets merged.

**Comment by MeisterP** [comment]
> Good to know #239 will fix this! Let's leave this issue open until the fix gets merged.

I can confirm that #239 fixes the issue for me as well.
