### ISSUE TITLE
ssh tab completion with host name

### ISSUE THREAD

**Issue by protist** [zimfw/zimfw#46]
For bug reports, please provide the following information:
- Zim commit ref: 6cb9d54
- Zsh version: 5.2
- $(uname -mosr): Linux 4.5.1-1-ARCH x86_64 GNU/Linux

Arch Linux, zim installed via AUR PKGBUILD (zsh-zim-git)
## Description

prezto offers tab completion of ssh with host names. e.g. if there are hosts defined in `~/.ssh/config`, you can tab complete with these. This seems to be missing in zim.
## Steps to reproduce

Type in `$ ssh f<tab>`. Expect host `foo` to be offered as a completion.

**Comment by Eriner** [comment]
I do not have this problem. I can tab complete hosts. Please link your .zimrc.

**Comment by protist** [comment]
I've pared down my `~/.zshrc`, `~/.zimrc`, and other files to exactly the same as those shipped by zim from the `templates` directory. I still hit this issue, but I may have described it poorly, so I will clarify. 

In `~/.ssh/config`, I have several entries such as the following.
```
Host foo
Hostname bar.com
IdentityFile ~/.ssh/protist@foo
User protist
```
I can type in `ssh <tab>`, and tab completion will offer a list of `remote host name`s, including `bar.com`. However, completing to `ssh bar.com` will not use settings in `~/.ssh/config`. Instead, one should normally connect with `ssh foo`. This expands the Host using the ssh config, using the correct identity file, port, etc.

Using zsh with `zim` will not tab complete to these Hosts. OTOH, prezto *does* offer to complete these Hosts.

**Comment by Eriner** [comment]
so, it tab completes the hostnames rather than the hosts?

**Comment by protist** [comment]
Yes. From memory, prezto offers to complete both.

**Comment by Eriner** [comment]
mine tab completes both.

Completion of remote hosts in menu:
"ssh \<tab\>"
```
 -- remote host name --
arch.localdomain               github.com                     localhost
arch                           localhost.localdomain          aur.archlinux.org
```

Tab completion of `Host` from `.ssh/config`
"ssh gi\<tab\>"
```
ssh gitlab
```

**Comment by protist** [comment]
With `zim`:
```
$ ssh a<tab>
 -- remote host name --
aur.archlinux.org
 -- login name --
avahi
```
With `prezto` installed (on top):
```
$ ssh a<tab>
 -- domain --
aur.archlinux.org
 -- host --
aur
```

I'm not really sure why the `login name` disappeared, but it shouldn't have really been in there in the first place.

**Comment by protist** [comment]
Since I've pared the config files down to your repository versions, it's odd that I see different behaviour to you. Would it be possible for you to post *your* personal files, so I can try with them?

**Comment by Eriner** [comment]
My personal files are basically the same as the template files. I haven't touched anything with ssh other than enabling and using the ssh agent feature.

**Comment by protist** [comment]
FWIW I tried enabling the `ssh` module, but that didn't make any difference. I followed instructions [here](http://serverfault.com/a/170481) to get it working, but I've no idea why it's not working in vanilla zim.

**Comment by protist** [comment]
Just a note for the code I'm currently using. It's sourced from the link above, but I've removed `known_hosts`, and added tab-completion for `rsync`.
```
h=()
if [[ -r ~/.ssh/config ]]; then
  h=($h ${${${(@M)${(f)"$(cat ~/.ssh/config)"}:#Host *}#Host }:#*[*?]*})
fi
if [[ $#h -gt 0 ]]; then
  zstyle ':completion:*:ssh:*' hosts $h
  zstyle ':completion:*:slogin:*' hosts $h
  zstyle ':completion:*:rsync:*' hosts $h
fi
```

**Comment by PatTheMav** [comment]
While I haven't found time to find a fix for this issue I can confirm the reported behavior.

Tab completion delivers ```known_hosts``` entries only, but not ```HOST``` entries from the SSH config (which contains the necessary combination of hostname, username and identity file).

**Comment by Eriner** [comment]
If someone wants to follow this up, this seems like a good place to start: http://www.zsh.org/mla/workers/2010/msg00535.html

**Comment by ratheesh** [comment]
I copied following lines from prezto (`modules/completion/init.zsh` - L95-99)

`zstyle -e ':completion:*:hosts' hosts 'reply=(
  ${=${=${=${${(f)"$(cat {/etc/ssh_,~/.ssh/known_}hosts(|2)(N) 2>/dev/null)"}%%[#| ]*}//\]:[0-9]*/ }//,/ }//\[/ }
  ${=${(f)"$(cat /etc/hosts(|)(N) <<(ypcat hosts 2>/dev/null))"}%%\#*}
  ${=${${${${(@M)${(f)"$(cat ~/.ssh/config 2>/dev/null)"}:#Host *}#Host }:#*\**}:#*\?*}}
)'`

After including this, ssh hostcompletion from `~/.ssh/config` works fine for me.

**Comment by PatTheMav** [comment]
TBH, I dunno _if_ @Eriner changed anything recently, but for some time now `tab` autocompletes to my aliases, so I figured that it was fixed somehow quite a while ago..

**Comment by protist** [comment]
@PatTheMav FWIW it's still broken for me, once I take out my fix from `~/.zshrc`.

**Comment by neeklamy** [comment]
- Zim commit ref:   dca1803
- Zsh version:      zsh 5.3.1 (x86_64-apple-darwin15.6.0)
- Darwin 15.6.0 x86_64 (10.11.6)

I haven’t made any customisations to Zim.

I do have ssh tab completion, *but*:

1. If I just `ssh <tab>` the servers I’ve set up in `~/.ssh/config` don’t appear. If I try `ssh di<tab>`, my DigitalOcean entry from `config` completes just fine.
2. If an entry in `~/.ssh/known_hosts` includes the same name (it ignores any TLDs and capitalisation), then it takes precedence over any related entry in `config`. So for example:

```
# known_hosts
digitalocean.com,12.345.67.89 ecdsa-sha2-nistp256 […]

# config
Host DigitalOcean
	HostName 12.345.67.89
	IdentityFile ~/.ssh/id_rsa
```

Hitting `ssh di<tab>` will always complete to `ssh digitalocean.com` On this second point, the fix is easy enough, just remove any domains from `known_hosts`.

The first issue remains though, recalling a list of configured domains from tab completion doesn’t work.

The code that @protist links to ([comment](#issuecomment-218034873)) fixes it though.

**Comment by Eriner** [comment]
Might be looking into seeing what can be learned from prezto's approach, as well as the issues and resolutions for omz: https://github.com/robbyrussell/oh-my-zsh/issues/4345

**Comment by Eriner** [comment]
Hi friends, it wouldn't let me tag some of you in the PR, but I believe #294 will solve this problem for everyone by forcing the completion to fallback to the `_ssh_hosts` builtin `~/.ssh/config` parsing. The only downside here is that the matching isn't ideal and it essentially matches by `host*` and thus IPs are also included in the initial list. Not a big enough deal to prevent PR imo.

**Comment by Eriner** [comment]
@protist, @PatTheMav, does that PR resolve the issue to your satisfaction?

**Comment by lnicola** [comment]
@Eriner, for whatever reason, `~/.ssh/config` completion is now working for me, even without #294.

**Comment by protist** [comment]
Thanks @Eriner! I compared the output to my [earlier comment](https://github.com/zimfw/zimfw/issues/46#issuecomment-214628303), and the `host` is now offered as an alternative! (To remind us, it's `aur` in the suggestions below.)
```
$ ssh a<tab>
-- remote host name --
aur                aur.archlinux.org
-- login name --
avahi
```

However, TBH I find this an inferior fix than what I have in `~/.zshrc`, because it suggests things that I'd prefer not in there, i.e. the hostname `aur.archlinux.org`, and the login name `avahi`. In my current code below, it _only_ suggests the `host` itself.
```
# ssh tab completion
h=()
if [[ -r ~/.ssh/config ]]; then
  h=($h ${${${(@M)${(f)"$(cat ~/.ssh/config)"}:#Host *}#Host }:#*[*?]*})
fi
if [[ $#h -gt 0 ]]; then
  zstyle ':completion:*:ssh:*' hosts $h
  zstyle ':completion:*:slogin:*' hosts $h
  zstyle ':completion:*:rsync:*' hosts $h
fi
# Prevent autocompletion of user names
zstyle ':completion:*:rsync:*' users
zstyle ':completion:*:ssh:*' users
```

You can see in my code the part suppressing the login names. I presume there's a way to suppress the plain `hostname` itself as well. So, long story short, it's definitely better than it was, but I'd probably still need to add code to fit my needs. Thanks again for persisting with this!

**Comment by Eriner** [comment]
@protist Cool. We can add more `zstyle` configurables later if necessary, but I believe this fixes the core issue and the built-in `_ssh_hosts` now behaves as expected and parses `~/.ssh/config` and not just `known_hosts` and `/etc/hosts`. 

Just as a short follow-up, you can define the `my_hosts` function with your filter to add only the `Host xyz` entries and not the `Hostname` entries. The fallthrough to the `_ssh_hosts` will glob anything like `host*`, as explained in my previous comment.
